# Generated by Django 4.1.7 on 2023-11-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Vendor's name")),
                ('contact_details', models.TextField(verbose_name='Contact information of the vendor')),
                ('address', models.TextField(verbose_name='Physical address of the vendor')),
                ('vendor_code', models.CharField(max_length=50, unique=True, verbose_name='Unique identifier for the vendor')),
                ('on_time_delivery_rate', models.FloatField(verbose_name='Percentage of on-time deliveries')),
                ('quality_rating_avg', models.FloatField(verbose_name='Average rating of quality based on purchase orders')),
                ('average_response_time', models.FloatField(verbose_name='Average time taken to acknowledge purchase orders')),
                ('fulfillment_rate', models.FloatField(verbose_name='Percentage of purchase orders fulfilled successfully')),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='Unique number identifying the PO')),
                ('order_date', models.DateTimeField(verbose_name='Date when the order was placed')),
                ('delivery_date', models.DateTimeField(verbose_name='Expected or actual delivery date of the order')),
                ('items', models.JSONField(verbose_name='Details of items ordered')),
                ('quantity', models.IntegerField(verbose_name='Total quantity of items in the PO')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20, verbose_name='Current status of the PO')),
                ('quality_rating', models.FloatField(blank=True, null=True, verbose_name='Rating given to the vendor for this PO')),
                ('issue_date', models.DateTimeField(verbose_name='Timestamp when the PO was issued to the vendor')),
                ('acknowledgment_date', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp when the vendor acknowledged')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.vendor', verbose_name='Link to the Vendor model')),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='HistoricPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of the performance record')),
                ('on_time_delivery_rate', models.FloatField(verbose_name='Historical record of on-time delivery rate')),
                ('quality_rating_avg', models.FloatField(verbose_name='Historical record of quality rating average')),
                ('average_response_time', models.FloatField(verbose_name='Historical record of average response time')),
                ('fulfillment_rate', models.FloatField(verbose_name='Historical record of fulfilment rate')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.vendor', verbose_name='Link to the Vendor model')),
            ],
            options={
                'verbose_name_plural': 'Historic Performances',
            },
        ),
    ]
