# Generated by Django 4.1.7 on 2023-11-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_purchase_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(default=0.0, verbose_name='Average time taken to acknowledge purchase orders'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0, verbose_name='Percentage of purchase orders fulfilled successfully'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0.0, verbose_name='Percentage of on-time deliveries'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(default=0.0, verbose_name='Average rating of quality based on purchase orders'),
        ),
    ]
