# Generated by Django 4.1.7 on 2023-11-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_purchase_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='po_number',
        ),
    ]
