# Generated by Django 4.1.7 on 2023-11-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_purchase_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='po_number',
            field=models.CharField(default='0', max_length=50, verbose_name='Unique number identifying the PO'),
        ),
    ]
