# Generated by Django 4.1.7 on 2023-11-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_purchase_po_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='po_number',
        ),
    ]
