# Generated by Django 4.1.7 on 2023-11-28 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_purchase_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 19, 40, 51, 676482, tzinfo=datetime.timezone.utc), verbose_name='Expected or actual delivery date of the order'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp when the PO was issued to the vendor'),
        ),
    ]
