# Generated by Django 4.1.7 on 2023-11-28 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_purchase_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 19, 45, 40, 396101, tzinfo=datetime.timezone.utc), verbose_name='Expected or actual delivery date of the order'),
        ),
    ]
