# Generated by Django 4.1.7 on 2023-11-29 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_purchase_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 9, 46, 57, 436946, tzinfo=datetime.timezone.utc), verbose_name='Expected or actual delivery date of the order'),
        ),
    ]
